###### English Premier League - season's final points table from https://www.espn.com/soccer/standings/_/league/ENG.1/

* Only completed season details are used in the Escape game
* The points table was downloaded into CSV files and stored in GitHub (espn.com forbids any http requests from python script, so the data was manually downloaded)
* Fine grained Personal Access Token(PAT) was created in Github for this specific repo
* Python dictionary object was created to clean the Team names

In [107]:
import csv #for writing into CSV file
import os
import pandas as pd
import numpy as np
import requests #to connect to github using restapi

In [108]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)  # Ignore the unnecessary noise of future warnings in the output

In [109]:
# Retrieve the contents of a GitHub repository folder using the API.
# Fine grained Personal Access Token(PAT) was created in Github for this specific repo
def get_github_folder_contents(username, repository, folder_path, token=None):

    api_url = f'https://api.github.com/repos/{username}/{repository}/contents/{folder_path}'
    headers = {'Authorization': f'token {token}'} if token else {}
    
    response = requests.get(api_url, headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Failed to fetch contents. Status code: {response.status_code}")
        return None

In [110]:
# Anonymizing the details before sharing
username = "marulsnesamony"
repository = "XXX"
folder_path = "XX"
token = "token"

In [ ]:
contents = get_github_folder_contents(username, repository, folder_path, token)
contents

In [112]:
# Read multiple CSV files from a GitHub folder using the API.

def read_multiple_files(username, repository, folder_path, token=None):

    contents = get_github_folder_contents(username, repository, folder_path, token)
    if not contents:
        return None
    
    
    list_dfs = []  # Storing the dataframes in a list
    i =0
    for item in contents:
        # Check if the item is a file and ends with .csv
#         i+=1
#         if i > 10:
#             return None
        if item['type'] == 'file' and item['name'].endswith('.csv') and not ("All_Years" in item['name']):
            download_url = item['download_url']
            season = item['name'][7:14]
            try:
                df = pd.read_csv(download_url)  #storing the file contents in a dataframe
                df['Season'] = season
                list_dfs.append(df)
            except Exception as e:
                print(f"Error reading {item['name']}: {e}")

    if list_dfs:
        combined_df = pd.concat(list_dfs, ignore_index=True)
        return combined_df
    else:
        return None

In [113]:
epl_df = read_multiple_files(username, repository, folder_path, token)
epl_df.head(30)

    Position            Team  PM   W   D   L  GF  GA  GD  PTS  Last5   Season
0          1         Man Utd  42  24  12   6  67  31  36   84  WWWWW  1992-93
1          2     Aston Villa  42  21  11  10  57  40  17   74  WWLLL  1992-93
2          3         Norwich  42  21   9  12  61  65  -4   72  LWLWD  1992-93
3          4       Blackburn  42  20  11  11  68  46  22   71  WWLWW  1992-93
4          5             QPR  42  17  12  13  63  55   8   63  WDDWW  1992-93
5          6       Liverpool  42  16  11  15  62  55   7   59  WWLLW  1992-93
6          7   Sheffield Wed  42  15  14  13  55  51   4   59  LDWLL  1992-93
7          8       Tottenham  42  16  11  15  60  66  -6   59  LDLLW  1992-93
8          9        Man City  42  15  12  15  56  51   5   57  LDWDL  1992-93
9         10         Arsenal  42  15  11  16  40  38   2   56  DDLWL  1992-93
10        11         Chelsea  42  14  14  14  51  54  -3   56  LWLWL  1992-93
11        12   Milton Keynes  42  14  12  16  56  55   1   54  LWDDL  1992-93
12        13         Everton  42  15   8  19  53  55  -2   53  LDDLW  1992-93
13        14   Sheffield Utd  42  14  10  18  54  53   1   52  LDWWW  1992-93
14        15   Coventry City  42  13  13  16  52  57  -5   52  DLLLD  1992-93
15        16    Ipswich Town  42  12  16  14  50  55  -5   52  LLWLW  1992-93
16        17       Leeds Utd  42  12  15  15  57  62  -5   51  DLDDD  1992-93
17        18     Southampton  42  13  11  18  54  61  -7   50  WLDLL  1992-93
18        19     Oldham Athl  42  13  10  19  63  74 -11   49  DLWWW  1992-93
19        20  Crystal Palace  42  11  16  15  48  61 -13   49  DLWDL  1992-93
20        21   Middlesbrough  42  11  11  20  54  75 -21   44  LLWWD  1992-93
21        22    Notts Forest  42  10  10  22  41  62 -21   40  WLDLL  1992-93
22         1         Man Utd  42  27  11   4  80  38  42   92  WWWWD  1993-94
23         2       Blackburn  42  25   9   8  63  36  27   84  LDWLD  1993-94
24         3       Newcastle  42  23   8  11  82  41  41   77  WWWLW  1993-94
25         4         Arsenal  42  18  17   7  53  28  25   71  DWDLL  1993-94
26         5       Leeds Utd  42  18  16   8  65  39  26   70  DLWDW  1993-94
27         6   Milton Keynes  42  18  11  13  56  53   3   65  DWWWL  1993-94
28         7   Sheffield Wed  42  16  16  10  76  54  22   64  DWDDD  1993-94
29         8       Liverpool  42  17   9  16  59  55   4   60  WLWLL  1993-94

In [114]:
epl_df.describe(include="all")

,Position,Team,PM,W,D,L,GF,GA,GD,PTS,Last5,Season
count,666.000000,666,666.000000,666.000000,666.000000,666.000000,666.000000,666.000000,666.000000,666.000000,586,666
unique,NaN,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,212,33
top,NaN,Everton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WWWWW,1992-93
freq,NaN,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,22
mean,10.599099,NaN,38.396396,14.285285,9.825826,14.285285,51.701201,51.701201,0.000000,52.645646,NaN,NaN
std,5.838163,NaN,1.196078,5.744667,2.953218,5.448294,15.186932,13.089256,24.998586,16.549873,NaN,NaN
min,1.000000,NaN,38.000000,1.000000,2.000000,0.000000,20.000000,15.000000,-69.000000,11.000000,NaN,NaN
25%,6.000000,NaN,38.000000,10.000000,8.000000,10.000000,41.000000,43.000000,-17.000000,41.000000,NaN,NaN
50%,11.000000,NaN,38.000000,13.000000,10.000000,15.000000,48.000000,52.000000,-5.000000,50.000000,NaN,NaN
75%,16.000000,NaN,38.000000,18.000000,12.000000,18.000000,61.000000,60.000000,15.000000,63.000000,NaN,NaN
max,22.000000,NaN,42.000000,32.000000,18.000000,30.000000,106.000000,104.000000,79.000000,100.000000,NaN,NaN

In [115]:
sorted(epl_df['Team'].unique())

['AFC Bournemouth',
 'Arsenal',
 'Aston Villa',
 'Barnsley',
 'Birmingham',
 'Blackburn',
 'Blackburn Rovers',
 'Blackpool',
 'Bolton',
 'Bolton Wanderers',
 'Bournemouth',
 'Bradford City',
 'Brentford',
 'Brighton',
 'Brighton & Hove Albion',
 'Brighton and Hove Albion',
 'Burnley',
 'Cardiff',
 'Charlton',
 'Chelsea',
 'Coventry City',
 'Crystal Palace',
 'Derby County',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull City',
 'Ipswich Town',
 'Leeds United',
 'Leeds Utd',
 'Leicester City',
 'Liverpool',
 'Luton Town',
 'Man City',
 'Man Utd',
 'Manchester City',
 'Manchester United',
 'Middlesbrough',
 'Milton Keynes',
 'Newcastle',
 'Newcastle United',
 'Norwich',
 'Norwich City',
 'Nottingham Forest',
 'Notts Forest',
 'Oldham Athl',
 'Portsmouth',
 'QPR',
 'Reading',
 'Sheffield United',
 'Sheffield Utd',
 'Sheffield Wed',
 'Southampton',
 'Stoke',
 'Stoke City',
 'Sunderland',
 'Swansea',
 'Swindon Town',
 'Tottenham',
 'Tottenham Hotspur',
 'Watford',
 'West Brom',
 'West Bromwich Albion',
 'West Ham',
 'West Ham United',
 'Wigan Athletic',
 'Wolverhampton Wanderers',
 'Wolves']

In [116]:
# Clean the team names to be consistent

team_dict = {
    "AFC Bournemouth": "Bournemouth",
    "Birmingham": "Birmingham City",
    "Blackburn": "Blackburn Rovers",
    "Bolton": "Bolton Wanderers",
    "Brighton": "Brighton & Hove Albion",
    "Brighton and Hove Albion": "Brighton & Hove Albion",
    "Cardiff": "Cardiff City",
    "Charlton": "Charlton Athletic",
    "Huddersfield": "Huddersfield Town",
    "Leeds Utd": "Leeds United",
    "Man City": "Manchester City",
    "Man Utd": "Manchester United",
    "Milton Keynes": "Milton Keynes Dons",
    "Newcastle": "Newcastle United",
    "Norwich": "Norwich City",
    "Notts Forest": "Nottingham Forest",
    "Oldham Athl": "Oldham Athletic",
    "QPR": "Queens Park Rangers", 
    "Sheffield Utd": "Sheffield United",
    "Sheffield Wed": "Sheffield Wednesday",
    "Stoke": "Stoke City",
    "Swansea": "Swansea City",
    "Tottenham": "Tottenham Hotspur",
    "West Brom": "West Bromwich Albion",
    "West Ham": "West Ham United",
    "Wolves": "Wolverhampton Wanderers"
}

In [117]:
epl_df = epl_df.replace(team_dict)
sorted(epl_df['Team'].unique())
epl_df.rename(columns = {'Team': 'Team Name'}, inplace=True)
epl_df.describe(include="all")

,Position,Team Name,PM,W,D,L,GF,GA,GD,PTS,Last5,Season
count,666.000000,666,666.000000,666.000000,666.000000,666.000000,666.000000,666.000000,666.000000,666.000000,586,666
unique,NaN,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,212,33
top,NaN,Manchester United,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WWWWW,1992-93
freq,NaN,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,22
mean,10.599099,NaN,38.396396,14.285285,9.825826,14.285285,51.701201,51.701201,0.000000,52.645646,NaN,NaN
std,5.838163,NaN,1.196078,5.744667,2.953218,5.448294,15.186932,13.089256,24.998586,16.549873,NaN,NaN
min,1.000000,NaN,38.000000,1.000000,2.000000,0.000000,20.000000,15.000000,-69.000000,11.000000,NaN,NaN
25%,6.000000,NaN,38.000000,10.000000,8.000000,10.000000,41.000000,43.000000,-17.000000,41.000000,NaN,NaN
50%,11.000000,NaN,38.000000,13.000000,10.000000,15.000000,48.000000,52.000000,-5.000000,50.000000,NaN,NaN
75%,16.000000,NaN,38.000000,18.000000,12.000000,18.000000,61.000000,60.000000,15.000000,63.000000,NaN,NaN
max,22.000000,NaN,42.000000,32.000000,18.000000,30.000000,106.000000,104.000000,79.000000,100.000000,NaN,NaN

In [118]:
epl_df

,Position,Team Name,PM,W,D,L,GF,GA,GD,PTS,Last5,Season
0,1,Manchester United,42,24,12,6,67,31,36,84,WWWWW,1992-93
1,2,Aston Villa,42,21,11,10,57,40,17,74,WWLLL,1992-93
2,3,Norwich City,42,21,9,12,61,65,-4,72,LWLWD,1992-93
3,4,Blackburn Rovers,42,20,11,11,68,46,22,71,WWLWW,1992-93
4,5,Queens Park Rangers,42,17,12,13,63,55,8,63,WDDWW,1992-93
...,...,...,...,...,...,...,...,...,...,...,...,...
661,16,Wolverhampton Wanderers,38,12,6,20,54,69,-15,42,NaN,2024-25
662,17,Tottenham Hotspur,38,11,5,22,64,65,-1,38,NaN,2024-25
663,18,Leicester City,38,6,7,25,33,80,-47,25,NaN,2024-25
664,19,Ipswich Town,38,4,10,24,36,82,-46,22,NaN,2024-25
665,20,Southampton,38,2,6,30,26,86,-60,12,NaN,2024-25

In [119]:
## folder to which the files will be written to
os.chdir("../Data")
epl_df.to_csv("Points_All_Years.csv", mode='w', index=False)